### ISSUE TITLE
Major release v2 can't be imported properly

### ISSUE THREAD

**Issue by opera-andreasl** [nervosnetwork/ckb-sdk-go#157]
I wasn't able to import the latest version of ckb-sdk-go into my project. I get the following error
`require github.com/nervosnetwork/ckb-sdk-go: version "v2.0.1" invalid: should be v0 or v1, not v2`

Listing valid versions doesn't include any v2 versions
```
go list -m -versions github.com/nervosnetwork/ckb-sdk-go
github.com/nervosnetwork/ckb-sdk-go v0.1.0 v0.2.0 v0.2.1 v0.3.0 v0.41.0 v0.42.0 v0.43.0 v0.43.1 v0.43.2-rc.1 v0.43.2 v0.43.3-beta.1 v0.100.0-beta.1 v0.100.0-beta.2 v0.101.0-beta.1 v0.101.0-beta.2 v0.101.1 v0.101.2 v0.101.3 v0.101.4 v0.101.5 v0.101.6 v1.0.0 v1.0.1 v1.0.2 v1.0.3 v1.0.4
``` 

I believe the issue is that Golang requires libraries to modify module path or add subdirectory when releasing major versions. 
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

**Comment by fjchen7** [comment]
Thanks for reporting. We will fix it in the next release.

**Comment by fjchen7** [comment]
We have fixed it in release [2.0.2](https://github.com/nervosnetwork/ckb-sdk-go/releases/tag/v2.0.2)

**Comment by ednailson** [comment]
Hi @fjchen7,

I still get the error for release 2.0.2

`go: errors parsing go.mod:
<PATH>: require github.com/nervosnetwork/ckb-sdk-go: version "v2.0.2" invalid: should be v0 or v1, not v2
`

**Comment by fjchen7** [comment]
Please try `require github.com/nervosnetwork/ckb-sdk-go/v2`

**Comment by ednailson** [comment]
@fjchen7 what do mean?

On go.mod I have something like: 
```
require (
	github.com/nervosnetwork/ckb-sdk-go/v2 v2.0.2
	github.com/nervosnetwork/ckb-sdk-go v2.0.2+incompatible
)
```
?

Because it still don't work.

**Comment by fjchen7** [comment]
You should remove `github.com/nervosnetwork/ckb-sdk-go v2.0.2+incompatible`.
